# Example configuration for generation-focused evaluation
# Uses a chat to retrieve contexts and evaluate both retrieval and generation quality.

generation:
  api_key: "ragflow-c1NzBmZjdhYTM1MDExZjBhMjlhMzdkMj"

  # Identify the chat to use (provide either chat_id or chat_name)
  # chat_id: "YOUR_CHAT_ID_HERE"
  chat_name: "simple_rag_qwen"
  size: 5
  
  # Optional overrides (defaults fall back to chat configuration)
  # base_url: "http://localhost:9380"
  
  # Retrieval metrics are still evaluated using the chat's retrieved doc IDs
  metrics:
    - recall
    
  k_values:
    - 5

dataset:
  path: "./dataset/tcm_sd_test_rc_direct.json"
  limit: 100  # Limit number of samples used for evaluation (null = all)

output:
  results_path: "results/evaluation_generation_600m_v3.json"
